Ft(update-profile): Update user profile
atlp-rwanda/Avengers-Phantom-FE pull request #39
Opened 2022-06-06 12:48 UTC by abraham-kwizera

## What does this PR do?

> Preview Current User Data and Update profile 

## Description of Task to be completed?

- [x] Added Skeleton to the Form 
- [x]  Add _Success/Unsuccessful Attempt_ messages 
- [x] fetch and update user data integration
- [x] Created a **view profile** page for displaying user's info before edit
- [x] Created an **update profile** page for implementing updates if the user wishes, which appears when clicked on the update profile button
- [x] Implemented FETCH and PATCH for manipulation of data relating to current user state managed by redux
- [x] Updated a build script to ensure that all dependencies in package.json are passed during installation

## How should this be manually tested?

1. clone git repo, if not yet done 
2. `cd Avengers-Phantom-FE` 
3. `npm i` or `npm install` to install dependencies 
4. `npm run dev` to start the server 
5. On a loaded **Homepage**, click on **Sign in** button in the menu bar
6. Enter valid credentials given by the System administrator 
7. After a valid sign-in attempt, you are redirected  to the main wall of the dashboard, click on the **Profile** tab in. ready to manipulate your data  :rocket:

**Sample Image description:** 
_1/3: Preview current user data:_
<img width="1440" alt="Screen Shot 2022-06-24 at 00 54 13" src="https://user-images.githubusercontent.com/60516506/175429048-ffe7ea85-8ecb-4957-b206-935054f48a3e.png">

_2/3: Form data manipulation:_ 
<img width="1440" alt="Screen Shot 2022-06-24 at 00 55 44" src="https://user-images.githubusercontent.com/60516506/175429244-5191ef8c-c275-49e0-a6ea-5b644833072e.png">

_3/3: Data after updates:_
<img width="1440" alt="Screen Shot 2022-06-24 at 00 56 04" src="https://user-images.githubusercontent.com/60516506/175429385-64642e43-b4ae-4865-b35f-cb534a074784.png">

END

2022-06-13 11:57 UTC, Byadiso approved these changes

2022-06-20 08:58 UTC, Anguandia commented
Hi @abraham-kwizera, good work! please take note of the following:
- Squash your commits to 1 when possible
- It would be good to add some screenshots to the description
- Liaise with @Gedeonir to get the issue of the failing build resolved

2022-06-20 12:21 UTC, Anguandia requested changes
Good work @abraham-kwizera , please address the few change requests suggested, then we'll be good to go

2022-06-20 12:21 UTC, Anguandia commented on src/Components/Homepage/MapSection.jsx
> +// import { MapContainer, TileLayer, useMap, Marker, Popup } from "react-leaflet";
Are you sure these are not needed? please consult with @Jeanndo before commenting the lines out

2022-06-20 12:21 UTC, Anguandia commented on src/Components/Homepage/MapSection.jsx
>  // console.log(TeslaData);
Please delete such commented-out lines if sure they are not needed

2022-06-20 12:21 UTC, Anguandia commented on src/Components/signin/Signin.jsx
>            console.log(data);
remove all unnecessary console.log statements

2022-06-24 07:59 UTC, Anguandia approved these changes

2022-06-24 13:11 UTC, merged