Ft crud operations buses
atlp-rwanda/Avengers-Phantom-FE pull request #44
Opened 2022-06-20 12:02 UTC by mugiisha

**What does this PR do?**
Create, Read, Update and Delete buses

**Description of Task to be completed?**
Integration of buses using redux
Created reducers, store, and actions for CRUD operations for buses.

**How should this be manually tested?**
step 1: clone git repo if not yet done.
step 2: cd Avengers-Phantom-FE.
step 3: yarn or npm install to install dependencies.
step 5: Use google chrome for better rendering (google chrome redux).

APIS Used
GET ---api/v1/buses for getting all buses
GET ---api/v1/buses/:uuid for getting bus details.
POST ---api/v1/buses/ for creating buses
PATCH --api/v1/buses/:uuid for updating bus

2022-06-20 13:00 UTC, Anguandia approved these changes
Hello @mugiisha, good work please use this [markdown](https://www.markdownguide.org/basic-syntax/) guide in subsequent PR descriptions. The headings especially should standout from the content

2022-06-20 13:06 UTC, Anguandia requested changes
Good job @mugiisha
- Please complete the _how to test this PR_ section with details of which page to navigate to
- what actions to execute once on the page
- what responses to expect
- screenshots of the process would be a great enhancement
- also, improve the styling of your PR description using this [markdown](https://www.markdownguide.org/basic-syntax/) guide. The headings especially should standout from their content/body

2022-06-23 08:39 UTC, Anguandia requested changes

2022-06-23 08:39 UTC, Anguandia commented on src/redux/Action/fetchallbuses.js
> +      const res = await axios.delete(`https://new-avengers-be-deploy.herokuapp.com/api/v1/buses/${id}`,{
Please, make it a point to read the backend url dynamically from the environment. I want to test with my local backend

2022-06-23 12:08 UTC, Anguandia approved these changes

2022-06-24 12:36 UTC, Byadiso commented on src/Components/dashboard/buses/Validations.jsx
>              // if (fieldValues.platenumber){
try to remove these commented lines, if they are not needed

2022-06-24 12:38 UTC, Byadiso commented on src/Components/signin/Signin.jsx
> +const baseUrl = process.env.BACKEND_URL
Is this working ? without dotenv configurated?

2022-06-24 13:01 UTC, mugiisha commented on src/Components/signin/Signin.jsx
> +const baseUrl = process.env.BACKEND_URL
dotenv is configurated in server.js

2022-06-25 20:57 UTC, abraham-kwizera reviewed
Hey @mugiisha you did greate, but i did left some comment reviews of suggested changes in some file. Let's work on it before we go 🚀

2022-06-25 20:57 UTC, abraham-kwizera commented on src/Components/dashboard/buses/BusDetail.jsx
> +import DashNavbar from "../dashnavbar/DashNavBar.jsx";
As we have a new integrated dashboard design, I hope that we don't need this `DashNavbar` still.

2022-06-25 20:57 UTC, abraham-kwizera commented on src/Components/dashboard/buses/BusDetail.jsx
> +    console.log(bus)
Let's remove these console log messages in this file.

2022-06-25 20:57 UTC, abraham-kwizera commented on src/Components/dashboard/buses/updateBus.jsx
> +  console.log(bus)
Lets remove the console logs messages in this file

2022-06-25 20:57 UTC, abraham-kwizera commented on src/redux/Action/fetchallbuses.js
> +      console.log(err.response.data)
As long as you have implemented a toast notification pop up, hope you have remove these console log message in this file.

2022-06-26 00:57 UTC, Byadiso approved these changes
Just squash the commits to 2 or 1 commit!

2022-06-27 07:54 UTC, abraham-kwizera approved these changes
@mugiisha just [Resolve Conflicts](https://github.com/atlp-rwanda/Avengers-Phantom-FE/pull/44#:~:text=package%2Dlock.json,webpack.config.js) and we go 🚀

2022-06-27 09:21 UTC, merged